Add delete user account
Filip1402/stylo-frontend pull request #10
Opened 2024-01-16 10:03 UTC by CroAnna

2024-01-16 11:10 UTC, Fr1k1 requested changes
Aj please dodaj neki alert ko npr React Sweet Alert jer ovo je malo loši UI...kao da pita hoćete li obrisati svoj račun jer to je ipak destruktivna radnja.

![image](https://github.com/Robert4361/stylo-frontend/assets/56409530/3f076af1-1f98-4d37-a049-cb077ca6f3d3)

2024-01-16 11:53 UTC, Fr1k1 approved these changes

2024-01-17 11:13 UTC, jbudak20-foi approved these changes
Looks good

2024-01-18 20:23 UTC, Filip1402 approved these changes

2024-01-18 20:53 UTC, merged